blood/blood/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings 
from django.conf.urls.static import static 
from blood1 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blood/signup',views.signup),
    url(r'^blood/donate/$',views.donate),
    url(r'^blood/contact/$',views.contact),
    url(r'^blood/feedback/$',views.feedback),
    url(r'^blood/tips/$',views.tips),
    url(r'^blood/find/$',views.find),
    url(r'^blood/donar_feedback/$',views.donor_feedback),
    url(r'^blood/apply_volunteer/$',views.apply_v),
    url(r'^blood/success/$',views.success),
    url(r'^blood/childprotection/$',views.childpro),
    url(r'^blood/startnonprofit/$',views.nonprofit),
    url(r'^blood/supporters/$',views.supporter),
    url(r'^blood/life_as_a_volunteer/$',views.life),
    url(r'^blood/donate_goods/$',views.goods),
    url(r'^blood/sponsorship/$',views.sponsor),
    url(r'^blood/mission_statement/$',views.mstatement),


]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

blood/blood1/urls.py
from django.conf.urls import url
from . import views

#urlpatterns = [
 #   url(r'signup', views.signup),
  #  url(r'home', views.index),
   # url(r'why', views.why),



#]

blood/blood1/models.py
from django.db import models

# Create your models here.

#donar registration form
class Register12(models.Model):
	blood_choice=(
		('a','a+'),
		('b','a-'),
		('c','o+'),
		('d','o-'),
		('e','b+')
		)
	gen=(
		('male','M'),
		('Female','F'),
		('Others','O')
		)
	name = models.CharField(max_length=50)
	emailid = models.EmailField()
	gender=models.CharField(choices=gen,max_length=30)
	blood_group = models.CharField(choices=blood_choice, max_length=128)
	state=models.CharField(max_length=30)
	city=models.CharField(max_length=30)
	def __str__(self):
		return self.name
# donar feedback form
class donar_feedback(models.Model):
	name = models.CharField(max_length=30)
	emailid = models.EmailField()
	inbox=models.CharField(max_length=500)
	def __str__(self):
		return self.name
# if  any one contact with us or if anyone have a query		
class contactus(models.Model):
	name = models.CharField(max_length=30)
	emailid = models.EmailField()
	subject=models.CharField(max_length=100)
	message=models.CharField(max_length=300)
	def __str__(self):
		return self.name
# Volunteer aplication form
class volunteer_apply(models.Model): 
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    emailid=models.EmailField()
    address=models.CharField(max_length=50)
    city=models.CharField(max_length=30)
    state=models.CharField(max_length=30)
    Pin_code=models.IntegerField()
    profile_image = models.ImageField(upload_to='images/',blank=True) 
    
    def __str__(self):
    	return self.emailid

blood/blood1/forms.py
from django import forms
from .models import *

class signup_form(forms.ModelForm):
	name=forms.CharField(widget=forms.TextInput(),required=True,max_length=100)
	emailid=forms.EmailField()
	state=forms.CharField(widget=forms.TextInput(),required=True,max_length=100)
	city=forms.CharField(widget=forms.TextInput(),required=True,max_length=100)


	class Meta():
		model= Register12
		fields = ['name','emailid','gender','blood_group','state','city']

class share_feedback(forms.ModelForm):
	name=forms.CharField(widget=forms.TextInput(),required=True,max_length=30)
	emailid=forms.EmailField(required=True)
	inbox=forms.CharField(widget=forms.TextInput(),required=True,max_length=500)

	class Meta():
		model=donar_feedback
		fields=['name','emailid','inbox']
class find_donor(forms.ModelForm):
	

	class Meta():
		model=Register12
		fields=['state','city','gender','blood_group']

class contact_form(forms.ModelForm):



	class Meta():
		model=contactus
		fields=['name','emailid','subject','message']

class volunterr_form(forms.ModelForm):
	



	class Meta():
		model=volunteer_apply
		fields=['first_name','last_name','emailid','address','city','state','Pin_code','profile_image']

blood/blood1/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.http import *
from .models import *
from .forms import *
from django.contrib import messages
from django.db.models import Q

def signup(request):
	if request.method == 'POST':
		form=signup_form(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/blood/signup/')
	else:
		form = signup_form()
	return render(request, 'signup.html', {'form':form})

def contact(request):
	if request.method == 'POST':
		form=contact_form(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/blood/contact/')
	else:
		form = contact_form()
	return render(request, 'contact.html', {'form':form})
def  feedback(request):
	if request.method == 'POST':
		form=share_feedback(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/blood/index/')
	else:
		form = share_feedback()
	return render(request, 'feedback.html', {'form':form})
def tips(request):
	if request.method == 'POST':
		form=find_donor(request.POST)
		return HttpResponseRedirect('blood/signup/')
	else:
		form = find_donor()
	return render(request, 'tips.html', {'form':form})

def find(request):
	if request.method == 'POST':
		form=find_donor(request.POST)
		return HttpResponseRedirect('/blood/find/')
	else:
		form=find_donor()
		query=Register12.objects.all()
	return render(request,"find.html",{'query':query,'form':form})

def donor_feedback(request):
	if request.method == 'POST':
		form=find_donor(request.POST)
		return HttpResponseRedirect('blood/signup/')
	else:
		form = find_donor()
		query=donar_feedback.objects.all()
	return render(request, 'donor_feedback.html', {'query':query,'form':form})

def donate(request):
	if request.method == 'POST':
		srch=request.POST['blood_group']
		if srch:
			match=Register12.objects.filter(Q(blood_group__icontains=srch))
			if match:
				return render(request,'find.html',{'sr':match})
			else:
				messages.error(request,'no result found')
		else:
			return HttpResponseRedirect('/blood/find/')
	return render(request,'donate.html')

def apply_v(request):
	if request.method == 'POST':
		form=volunterr_form(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			return redirect('/blood/success/')
	else:
		form = volunterr_form()
	return render(request, 'apply_volunteer.html', {'form':form})
def success(request):
	return HttpResponse('successfuly uploaded')

def childpro(request):
    return render(request,'child_protection.html')

def nonprofit(request):
    return render(request,'startnonprofit.html')
def supporter(request):
    return render(request,'supporters.html')
def life(request):
    return render(request,'life_as_a_volunteer.html')
def goods(request):
    return render(request,'donategoods.html')
def sponsor(request):
    return render(request,'sponsor.html')
def mstatement(request):
    return render(request,'missionstatement.html')
def home(request):
    return render(request,'home.html')

blood/blood1/templates/apply_volunteer.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Blood donner</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <style>
  /* bg for background coclor */
  *{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
html, body {
    max-width: 100%;
    overflow-x: hidden;
}
  .nav{
    overflow: hidden;
    height:70px;
    width: 100%;
    background-color:#655d5d;
    text-align: center;
    opacity: 0.6;
    }
  .nav ul{
    display: inline-flex;
    list-style: none;
    color: white;
  }
  .nav ul li{
    width: 120px;
    margin: 10px;
    padding: 10px;
  }
  .nav ul li a{
    text-decoration: none;
    color: white;
  }
  .nav ul li:hover{
    background-color: #655d5d;
    border-radius: 3px;
  }
  .nav-1{
    display: none;
    position: relative;
  }
  .nav ul li:hover .nav-1{
    display: block;
    position: absolute;
    background-color: #655d5d;
  }
  .nav ul li:hover .nav-1 ul{
    display: block;
    margin:10px;
  }
  .nav ul li:hover .nav-1 ul li{
    width: 150px;
    padding: 10px;
    border-bottom:1px dotted #fff;
  }
  .nav ul li:hover .nav-1 ul li:last-child{
    border-bottom: none;
  }
  .nav ul li:hover .nav-1 ul li a:hover{
    color: black;
  }
  .nav-2{
    display: none;
  }
  .hover-me:hover .nav-2{
    position: absolute;
    display: block;
    margin-top: -40px;
    margin-left: 140px;
    background-color: #655d5d;

  }
 .form1{
   background-image: url({% static 'blood1/vold1.jpg' %});
   background-size: cover;
   background-position: center;
   height: 630px; 
 }
 .form1-back{
  position:absolute;
  margin-left: 60px;
  margin-top: 181px;
 }
 .v_form{
  background-image: url({% static 'blood1/application.jpg' %});
   background-size: cover;
   background-position: center;
   margin-top: -10px;
   height: 300px;
   
 }
 input[type=text]{
  width:350px;
  margin-left: 10px;
 }
 p{
  margin-left: 10px;
 }

 .footer{
  width: 100%;
  height:100px;
  background-attachment: #655d5d;
  text-align: center;
  padding-top: 10px;

 }
</style> 
</head> 
<body>
  <form method = "post" enctype="multipart/form-data"> 
  {% csrf_token %}
  
  <div class="form1">
    <div class="form1-back"><p style="
    font-size: 40px; color: #655d5d"><b>Children can make you smile anytime!! <br>But when you will make them smile??!!<br></b>
    <p style="font-size: 40px;">  Welcome To Our Family</p>
  </div>
    <div class="nav">
  
  <ul>
    <li><a href="#"> Home</a></li>
    <li ><a href="#">About Us</a>
      <div class="nav-1">
        <ul>
          <li div class="hover-me"><a href="#">Our Mission</a>
            <div class="nav-2">
        <ul>
          <li><a href="#">Mission Statement</a></li>
          <li><a href="#">Statement Of Faith</a></li>
          <li><a href="#">Board Of Directors</a></li>
          <li><a href="#">Our Staff</a></li>
          <li><a href="#">History</a></li>
        </ul>
      </div>
          </li>
          <li div class="hover-me"><a href="#">Our Pillars</a>
               <div class="nav-2">
        <ul>
          <li><a href="#">Our Hostel</a></li>
          <li><a href="#">Our School</a></li>
          <li><a href="#">Agricultural Projects</a></li>
          <li><a href="#">Leprosy Mission</a></li>
          <li><a href="#">Disaster Relief</a></li>
          <li><a href="#">Vocational Training</a></li>
        </ul>
      </div>

          </li>
          <li div class="hover-me" ><a href="#">More Info</a>
            <div class="nav-2">
        <ul>
          <li><a href="#">Newsletter</a></li>
          <li><a href="#">National Geographic Photocamp</a></li>
          <li><a href="#">Download Brochure</a></li>
          <li><a href="#">Financial & Reports</a></li>
          <li><a href="#">Our Blog</a></li>
        </ul>
      </div>
          </li>
          <li><a href="#">Summer Games</a></li>
        </ul>
      </div>
    </li>
    <li><a href="#">Support</a>
      <div class="nav-1">
        <ul>
          <li><a href="#">Sponsor A Child</a></li>
          <li><a href="#">Donate Financially</a></li>
          <li><a href="#">Donate Goods In Kind</a></li>
        </ul>
      </div>
    </li>
    <li><a href="#">Volunteer</a>
      <div class="nav-1">
        <ul>
          <li><a href="/blood/life_as_a_volunteer/">Life As A Volunteer</a></li>
          <li><a href="/blood/apply_volunteer/">Apply To Volunteer</a></li>
        </ul>
      </div>
    </li>
    <li><a href="#">Other</a>
      <div class="nav-1">
        <ul>
          <li><a href="#">Adoption</a></li>
          <li><a href="/blood/childprotection/">Child Protection</a></li>
          <li><a href="/blood/policies/">Policies</a></li>
          <li><a href="/blood/startnonprofit/">Starting A Non-Profit</a></li>
          <li><a href="/blood/supporters/">Our Supporters</a></li>
        </ul>
      </div>
    </li>
    <li><a href="/blood/contact/">Contact Us</a>
      <a href="/blood/donate/"> <button style="margin-top: -41px;margin-left: 169px;" type="button" class="btn btn-warning">Donate</button></a>
  </ul>
  </div>
</div>
<div class="v_form">
    <h1 style="margin-top: 10px; text-align: center; padding-top: 20px;">Volunteer Application Form</h1>
    
    <div class="row">
      <div class="col-sm-6">
    <p><label for="id_first_name">First name:</label><input type="text" name="first_name" maxlength="30" required id="id_first_name"></p>
  </div>
    <div class="col-sm-6">
<p><label for="id_last_name">Last name:</label> <input type="text" name="last_name" maxlength="30" required id="id_last_name"></p>
</div>
</div>
<div class="row">
  <div class="col-sm-6">
<p><label for="id_emailid">Emailid: &nbsp  &nbsp &nbsp</label> <input style="width: 405px;" type="email" name="emailid" required id="id_emailid"></p>
</div>
<div class="col-sm-6">
<p><label for="id_address">Address: &nbsp &nbsp</label> <input type="text" name="address" required id="id_address"></p>
</div>
</div>
<div class="row">
  <div class="col-sm-6">
<p><label for="id_city">City: &nbsp &nbsp &nbsp &nbsp</label> <input type="text" name="city" required id="id_city"></p>
</div>
<div class="col-sm-6">
<p><label for="id_state">State: &nbsp &nbsp &nbsp &nbsp &nbsp</label> <input type="text" name="state" required id="id_state"></p>
</div>
</div>
<div class="row">
  <div class="col-sm-6">
<p><label for="id_Pin_code">Pin code: &nbsp</label> <input  type="number" name="Pin_code" required id="id_Pin_code"></p>
</div>
<div class="col-sm-6">
<p><label for="id_profile_image">Profile image:</label> <input style="margin-left: 150px; margin-top: -24px;" type="file" name="profile_image" accept="image/*" id="id_profile_image"></p>
</div>
</div>
      <button style="margin-left: 450px;width: 200px;" type="submit">submit</button>
    </div>
    <div class="footer">
    <p style="padding-top: 10px;">@Copy right reserved</p>
  </div>
</body>
  </html>

blood/blood1/templates/contact.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Blood donner</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <style>
  /* bg for background coclor */
  
  *{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
html, body {
    max-width: 100%;
    overflow-x: hidden;
}
  .nav{
    overflow: hidden;
    height:70px;
    width: 100%;
    background-color:#655d5d;
    text-align: center;
    opacity: 0.6;
    }
  .nav ul{
    display: inline-flex;
    list-style: none;
    color: white;
  }
  .nav ul li{
    width: 120px;
    margin: 10px;
    padding: 10px;
  }
  .nav ul li a{
    text-decoration: none;
    color: white;
  }
  .nav ul li:hover{
    background-color: #655d5d;
    border-radius: 3px;
  }
  .nav-1{
    display: none;
    position: relative;
  }
  .nav ul li:hover .nav-1{
    display: block;
    position: absolute;
    background-color: #655d5d;
  }
  .nav ul li:hover .nav-1 ul{
    display: block;
    margin:10px;
  }
  .nav ul li:hover .nav-1 ul li{
    width: 150px;
    padding: 10px;
    border-bottom:1px dotted #fff;
  }
  .nav ul li:hover .nav-1 ul li:last-child{
    border-bottom: none;
  }
  .nav ul li:hover .nav-1 ul li a:hover{
    color: black;
  }
  .nav-2{
    display: none;
  }
  .hover-me:hover .nav-2{
    position: absolute;
    display: block;
    margin-top: -40px;
    margin-left: 140px;
    background-color: #655d5d;
}
 .form1{
   background-image: url({% static 'blood1/contact1.jpg' %});
   background-size: cover;
   background-position: center;
   height: 640px; 
 }
 .form1-back{
  position:absolute;
  margin-left: 60px;
  margin-top: 181px;
 }
 .v_form{
  background-image: url({% static 'blood1/application.jpg' %});
   background-size: cover;
   background-position: center;
   margin-top: -10px;
   height: 300px;
   
 }
 input[type=text]{
  width:350px;
  margin-left: 10px;
 }
 p{
  margin-left: 10px;
 }
 .footer{
  width: 100%;
  height:100px;
  background-attachment: #655d5d;
  background-color: #4b4949;
  text-align: center;
  padding-top: 15px;
  margin-top: 10px;

 }
.add1{
  background-image: url("{% static 'blood1/add1.jpg' %}");
  height: 300px;
  opacity: 0.8;
  margin-top: 20px;
  margin-left: 19px;
  margin-right: -28px;

}
.add2{
  background-color: #d6bfbf;
  height: 300px;
  margin-top: 20px;
  opacity: 0.3;
}
</style>
</head>
<body>
  <form method="post" action="">
  {% csrf_token %}
  <div class="form1">
    <div class="form1-back"><p style="
    font-size: 40px; color: #655d5d">Contact With  Us</p>
  </div>
  
    <div class="nav">
    <img style="float: left;height: 40px; margin-top: 10px; margin-left: 100px;" src="{% static 'blood1/logo.jpg' %}" ><ul>
    <li><a href="#"> Home</a></li>
    <li ><a href="#">About Us</a>
      <div class="nav-1">
        <ul>
          <li div class="hover-me"><a href="#">Our Mission</a>
            <div class="nav-2">
        <ul>
          <li><a href="#">Mission Statement</a></li>
          <li><a href="#">Statement Of Faith</a></li>
          <li><a href="#">Board Of Directors</a></li>
          <li><a href="#">Our Staff</a></li>
          <li><a href="#">History</a></li>
        </ul>
      </div>
          </li>
          <li div class="hover-me"><a href="#">Our Pillars</a>
               <div class="nav-2">
        <ul>
          <li><a href="#">Our Hostel</a></li>
          <li><a href="#">Our School</a></li>
          <li><a href="#">Agricultural Projects</a></li>
          <li><a href="#">Leprosy Mission</a></li>
          <li><a href="#">Disaster Relief</a></li>
          <li><a href="#">Vocational Training</a></li>
        </ul>
      </div>

          </li>
          <li div class="hover-me" ><a href="#">More Info</a>
            <div class="nav-2">
        <ul>
          <li><a href="#">Newsletter</a></li>
          <li><a href="#">National Geographic Photocamp</a></li>
          <li><a href="#">Download Brochure</a></li>
          <li><a href="#">Financial & Reports</a></li>
          <li><a href="#">Our Blog</a></li>
        </ul>
      </div>
          </li>
          <li><a href="#">Summer Games</a></li>
        </ul>
      </div>
    </li>
    <li><a href="#">Support</a>
      <div class="nav-1">
        <ul>
          <li><a href="#">Sponsor A Child</a></li>
          <li><a href="#">Donate Financially</a></li>
          <li><a href="#">Donate Goods In Kind</a></li>
        </ul>
      </div>
    </li>
    <li><a href="#">Volunteer</a>
      <div class="nav-1">
        <ul>
          <li><a href="/blood/life_as_a_volunteer/">Life As A Volunteer</a></li>
          <li><a href="/blood/apply_volunteer/">Apply To Volunteer</a></li>
        </ul>
      </div>
    </li>
    <li><a href="#">Other</a>
      <div class="nav-1">
        <ul>
          <li><a href="#">Adoption</a></li>
          <li><a href="/blood/childprotection/">Child Protection</a></li>
          <li><a href="/blood/policies/">Policies</a></li>
          <li><a href="/blood/startnonprofit/">Starting A Non-Profit</a></li>
          <li><a href="/blood/supporters/">Our Supporters</a></li>
        </ul>
      </div>
    </li>
    <li><a href="/blood/contact/">Contact Us</a>
      <a href="/blood/donate/"> <button style="margin-top: -41px;margin-left: 169px;" type="button" class="btn btn-warning">Donate</button></a>
  </ul>
  </nav>
</div>
      </div>
      </div>
      <h1 style="text-align: center;"> Contact Us</h1>
  <p style="margin-left: 70px; margin-right: 40px; font-size: 20px;">If you would like to contact our orphanage, if you have any questions/concerns/thoughts or if you just want to say “hello” please feel free to contact us using the form below. We would love to hear from you and will endeavor to reply as soon as possible. 
</p>
<div class="row">
  <div class="col-sm-6">
<p><label for="id_name">&nbsp;Name:</label> <input type="text" name="name" maxlength="30" required id="id_name"></p>
</div>
<div class="col-sm-6">
<p><label for="id_emailid">Emailid:</label> <input type="email" name="emailid" required id="id_emailid"></p>
</div>
<p><label for="id_subject">&nbsp; &nbsp;Subject:</label> <input type="text" name="subject" maxlength="100" required id="id_subject"></p>
<p><label for="id_message"> &nbsp;&nbsp;&nbsp;Message:</label> <textarea style="width: 700px;" name="message" cols="40" rows="10" maxlength="100" required id="id_message">
</textarea></p>
      <button style="margin-left: 450px;width: 100px;" type="submit">submit</button>
      <div class="row">
        <div class="col-sm-6">
<div class="add1">
  <h1 style="text-align: center;color: white;">Address</h1>
</div>
</div>
<div class="col-sm-6">
<div class="add2">
  <h1 style="text-align: center;color: black;">Phone</h1>
</div>
</div>
  </div>

<div class="footer">
  <p style="margin-top: 10px;">@copyright reserved</a></p> 
</footer>
	</body>
  </html>

blood/blood1/templates/feedback.html
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
	<style>
		.bg-1{
			background-color: #484545;
			height:500px;
      width:100%;
		}
		.bg-4{
  			background-color: #2f2f2f;
  			color: #ffffff;
  			height:80px;
  			margin-top: -14px
  		}
  		.navbar {
  			padding-top: 15px;
  			padding-bottom: 15px;
  			border: 0;
  			border-radius: 0;
  			margin-bottom: 0;
  			font-size: 12px;
  			letter-spacing: 5px;
}
    .bg-2{
      background-color: #f0e9e9;
      height:457px;
      width:706px;
      margin-top: 20px;
    }

.navbar-nav li a:hover {
  color: #1abc9c !important;
}
	</style>
<body>
	<form method="post" action="">
		{% csrf_token %}
		<nav class="navbar navbar-inverse">
  		<div class="container">
    	<div class="navbar-header">
        <a class="navbar-brand" href="/blood/index">Blood Donation</a>
      	<h1 style="margin-left:295px;margin-top: 20px"><b>Share Your Experience</b></h1>
    	</div>
  </div>
</nav> 
		<div class="container-fluid bg-1 text-center">
      <div class="container-fluid bg-2">
        <h1> Share your experience</h1>
        
			{{ form.as_p }}
			<button type="submit">submit</button>
    </div>
	</div>
</div>
</form>

	</div>
	
	<footer class="container-fluid bg-4 text-left">
  <p>Copyright © IndianBloodBank.com. 2019. All rights reserved</p> 
</footer>
</body>
</head>
</html>

blood/blood1/templates/signup.html
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
	<style>
		.bg-1{
			background-color: #484545;
			height:500px;
      width:100%;
		}
		.bg-4{
  			background-color: #2f2f2f;
  			color: #ffffff;
  			height:80px;
  			margin-top: -14px
  		}
  		.navbar {
  			padding-top: 15px;
  			padding-bottom: 15px;
  			border: 0;
  			border-radius: 0;
  			margin-bottom: 0;
  			font-size: 12px;
  			letter-spacing: 5px;
}
    .bg-2{
      background-color: #f0e9e9;
      height:457px;
      width:706px;
      margin-top: 20px;
    }

.navbar-nav li a:hover {
  color: #1abc9c !important;
}
	</style>
<body>
	<form method="post" action="">
		{% csrf_token %}
		<nav class="navbar navbar-inverse">
  		<div class="container">
    	<div class="navbar-header">
        <a class="navbar-brand" href="/blood/home/">Blood Donation</a>
      	<h1 style="margin-left:295px;margin-top: 20px">Create your new account</h1>
    	</div>
  </div>
</nav> 
		<div class="container-fluid bg-1 text-center">
      <div class="container-fluid bg-2">
        <h1> Sign Up</h1>
			{{ form.as_p }}
			<button type="submit">submit</button>
    </div>
	</div>
</div>
</form>

	</div>
	
	<footer class="container-fluid bg-4 text-left">
  <p>Copyright © IndianBloodBank.com. 2019. All rights reserved</p> 
</footer>
</body>
</head>
</html>